# Generated by Django 3.2 on 2025-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_city_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('count', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='', verbose_name='Logo')),
            ],
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='CityModelFrom',
        ),
    ]
