# Generated by Django 3.2 on 2025-03-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cityform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待执行'), (2, '正在执行'), (3, '已完成'), (4, '失败'), (5, '已撤单')], default=1, verbose_name='状态'),
        ),
    ]
