# Generated by Django 3.2 on 2025-03-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_ip', models.CharField(max_length=18, verbose_name='登录ip')),
                ('login_city', models.CharField(max_length=64, verbose_name='登录城市')),
                ('login_province', models.CharField(max_length=64, verbose_name='登录省份')),
                ('login_device_type', models.CharField(max_length=64, verbose_name='设备类型')),
                ('login_os', models.CharField(max_length=64, verbose_name='操作系统')),
                ('login_browser', models.CharField(max_length=64, verbose_name='浏览器名称')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='web.administrator', verbose_name='管理员')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='web.customer', verbose_name='客户')),
            ],
        ),
    ]
