# Generated by Django 3.2 on 2025-03-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_browser',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='浏览器名称'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='登录城市'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_device_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_os',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_province',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='登录省份'),
        ),
    ]
